### ISSUE TITLE
delete rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk 

### ISSUE THREAD

**Issue by bestia-dev** [kornelski/crev-proofs#1]
When `cargo crev fetch trusted` I got this warning:
WARN: URL for rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk is not known yet
I found that this Id is in your trust crev file 2020-09-qnSWXg.proof.crev
You can find it in ~/.config/crev/proofs/.../.../trust
Can you manually delete these lines from this file with a text editor?
Or use `cargo crev trust --level untrust rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk`

----- BEGIN CREV PROOF -----
kind: trust
version: -1
date: "2020-09-14T16:09:50.233555+01:00"
from:
  id-type: crev
  id: rBGRONmiSLmELT1SuRDDScgLcoJl8mTdEbZqz1XCesM
  url: "https://github.com/kornelski/crev-proofs"
ids:
  - id-type: crev
    id: rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk
trust: high
comment: |-
  Rotating key
----- SIGN CREV PROOF -----
LX38bnYh5YPjL6FWSP5Csk5HunYPUqHFfeLyY_V6jsMycN5l4gNQNBPLtNNjsRwJ5SBhIwC2n9axnaf86HCdBg
----- END CREV PROOF -----

----- BEGIN CREV PROOF -----
kind: trust
version: -1
date: "2020-09-14T16:26:02.262017+01:00"
from:
  id-type: crev
  id: rBGRONmiSLmELT1SuRDDScgLcoJl8mTdEbZqz1XCesM
  url: "https://github.com/kornelski/crev-proofs"
ids:
  - id-type: crev
    id: rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk
trust: high
comment: |-
  Key rotation
----- SIGN CREV PROOF -----
sRnHLjLGlhtpdALcY-poCyOP9-GojyVH5TpABIGoziPimVunXWbEzMheWf2vBYuowDowWe2YG_PQz0QUcU-rAQ
----- END CREV PROOF -----

**Comment by kornelski** [comment]
I think these types of errors will be common. You can't rely on everyone's repos being flawless, so it needs a better handling in cargo-crev.

**Comment by LucianoBestia** [comment]
There can be a lot of different solutions. But I am now thinking theoretically about the "web of trust".
It is just a warning after I use `cargo crev fetch trusted`, but it is annoying because it has nothing to do with me.

Let's say: I trust "developer_1". It means I trust his reviews, but I also trust his choice of trusted people.
If he trusts a developer/repository, that does not exist anymore, what does it say about him?
Maybe I cannot trust his "choice of trusted people" if he does not pay attention to this simple warning. 
Maybe he does not pay attention at all anymore. Maybe in his "trusted people", there is a developer that was ok in the past but is a rogue player now and should be removed. He does not pay attention to this either.

The best way to gain more trust in the community is that I directly alert "developer_1" that something is wrong in his "crev data". I think that the "Github Issues" on the crev-proofs repo is the best way.  
If he is still active, he will find it helpful that somebody saw the problem and alerted him. He can solve the problem easily. 
If he is not active anymore and does not respond then it is better to not trust this "crev-proof repo", because it is unmaintained.

I think that it is good for the "web of trust", that we can communicate with other developers about their "crev data", reviews, ratings, and who we trust.

**Comment by LucianoBestia** [comment]
My conclusion in short:
I think that "human interaction" is good for the "web of trust" of crev. 
It builds trust when we can communicate directly using "Issues" or "Discussion" on github in our crev-proofs repo.

**Comment by dpc** [comment]
> I think these types of errors will be common. You can't rely on everyone's repos being flawless, so it needs a better handling in cargo-crev.

It's not like the command fails or anything. It downloads what it can, prints a one-line warning for what it can not.

> If he trusts a developer/repository, that does not exist anymore, what does it say about him?

Nothing. It just means that someone deleted their proof repository for whatever reason. Trusting someone with a `level: low` is not a marriage or lifetime friendship, but a sign that this person most probably is not going to be malicious, and is not a bot.

>  Maybe I cannot trust his "choice of trusted people" if he does not pay attention to this simple warning.

It's just a warning.


>  It builds trust when we can communicate directly using "Issues" or "Discussion" on github in our crev-proofs repo.

People don't have to use github, and in the future there might not be using git repos at all (it just doesn't scale beyond a point). So while people can try to communicate with each other it, it can't be guaranteed. Also, it might be too much effort, so people might want to just completely disable issues/PR/discussion and not have bother with it. Anyone is free to just not trust given ID.


Note that in the latest version of `cargo-crev` you can just:

```
cargo crev trust --overrides rH6k4Foaqr8nM2IeNs2G2BTHEyLGD6kUn0suj89iCYk
```

and then uncomment `overrides:` list and kornelski's ID list item, to mark that you want to ignore that trust relation. Anyone trusting you more than kornelski, will also ignore that trust. This was implemented precisely to let people due a minor corrections (overrides) and be more selective when they have a reason for it.
